### ISSUE TITLE
Timeout, no reconnect?

### ISSUE THREAD

**Issue by gizmocuz** [robertklep/nefit-easy-http-server#1]
Small issue found....

When starting the server, and doing a request, works
waiting some minutes, and doing a request results in a timeout
but it seems the connection is never rebuild, from this moment there is always a timeout

Is it possible to send a ping to the server every xx seconds when connected, or request some state
and/or if there is really a timeout, that the connection is rebuild ?

Error: REQUEST_TIMEOUT at null. (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:109:23) at Timer.listOnTimeout (timers.js:92:15)

**Comment by robertklep** [comment]
Yeah, I can reproduce. It's not that the connection is gone, it's that the backend stops responding. I'll see if issuing ping-like commands helps keep the connection active.

**Comment by robertklep** [comment]
Just released [v2.1.0](https://github.com/robertklep/nefit-easy-http-server/tree/v2.1.0) which sends periodic pings that keep the connection active.

**Comment by gizmocuz** [comment]
Thanks!
