### ISSUE TITLE
Endpoint to set temperature?

### ISSUE THREAD

**Issue by balk77** [robertklep/nefit-easy-http-server#10]
Hi, I would like to set the temperature via the http server, similar to ’easy set temperature "20"' via the cli. Is that possible? I could not find an endpoint in the list.

**Comment by robertklep** [comment]
The last example in the [README](https://github.com/robertklep/nefit-easy-http-server#http-to-xmpp-bridge) shows how to set the temperature:
```
curl -XPOST http://127.0.0.1:3000/bridge/heatingCircuits/hc1/temperatureRoomManual -d '{"value":20}' -H 'Content-Type: application/json'
```

(you may have to change `127.0.0.1:3000` to point to the correct IP-address if you're not running the HTTP server on the local machine)

The `easy` command line tools actually uses three endpoints:
```
/heatingCircuits/hc1/temperatureRoomManual          { "value" : 20 }
/heatingCircuits/hc1/manualTempOverride/status      { "value" : "on" }
/heatingCircuits/hc1/manualTempOverride/temperature { "value" : 20 }
```

**Comment by balk77** [comment]
Clear! Thanks!
