### ISSUE TITLE
Easy-server now needs Node.js 6.0.0 of later?

### ISSUE THREAD

**Issue by FrankvanCoeverden** [robertklep/nefit-easy-http-server#13]
As of this morning the http server did not function properly and gave a steady XMPP authentication error. I have found that updating Node.js from 4.9.1 to version 10.2.1 ( latest stable version ) did resolve this issue.

I think the readme has yet to be updated? Could you please verify?

Thanks

Frank

**Comment by robertklep** [comment]
There's actually two things that happened, the major one being that the Nefit/Bosch backend changed early yesterday, which broke the library that communicates with it (see #12).

I pushed an update yesterday afternoon which solved that problem, but the result of that is that Node versions 6 and lower are not supported anymore. You see this when you install the package:
```
$ npm i nefit-easy-http-server
npm WARN engine nefit-easy-commands@2.0.0: wanted: {"node":">=6"} (current: {"node":"4.6.1","npm":"2.15.9"})
npm WARN engine nefit-easy-core@3.0.0: wanted: {"node":">=6"} (current: {"node":"4.6.1","npm":"2.15.9"})
```

I just published `nefit-easy-http-server@4.0.1` with an updated README and an updated configuration so it will show the same warning for `nefit-easy-http-server` as well (sadly, there isn't a configuration option that will prevent installation if the used Node version is too old).

So after you installed Node v10 I pushed an updated version of the library which fixed things. However, Node v10 in itself isn't a requirement.
