### ISSUE TITLE
XMPP authentication failure (even after installing easy-server v4.0.1)

### ISSUE THREAD

**Issue by mchangsp** [robertklep/nefit-easy-http-server#14]
Since a few days I get the error 
"XMPP authentication error".
I found https://github.com/robertklep/nefit-easy-http-server/issues/12
and upgraded easy-server.
The error is still there.
Any tips?

I upgraded various packages. This is the result:
Raspberry Pi with Raspian jessie
npm -v: 6.1.0
node -v: v9.9.0
easy-server -v: 4.0.1

regards
Marc

**Comment by robertklep** [comment]
If you run the server with debugging enable, it will log a lot of data that might provide a clue why it's not working for you.

Start it like this:
```
env DEBUG=* easy-server
```

Please post the output here (I don't think it will contain any sensitive data, but please make sure it doesn't).

**Comment by mchangsp** [comment]
Hi Robert,
The error output is in the err.txt file.
I blanked out some data shown with ***blanked out***
[err.txt](https://github.com/robertklep/nefit-easy-http-server/files/2064017/err.txt)

Thanks for looking into the matter.

**Comment by robertklep** [comment]
The output in the logfile isn't from the latest version of the server, but from the previous (non-functioning) version.

I suspect that you have two versions of `easy-server` installed, one in `/usr/bin` and one in `/usr/local/bin`, and the wrong one is started (probably the one in `/usr/bin`).

This can happen when you have upgraded Node.js to a version that isn't available in the regular "jessie" repo (perhaps through a PPA).

You can find out the versions of the server as follows:
```
/usr/bin/easy-server -v
/usr/local/bin/easy-server -v
```

And remove the file that outputs the outdated version.

**Comment by mchangsp** [comment]
Robert, you are the best!
I indeed had an old version in /usr/bin/easy-server.
For a quick hack I deleted that version and now the easy-server is up and running again.

Thanks Thanks Thanks!

regards
Marc
