### ISSUE TITLE
MAX_RETRIES_REACHED

### ISSUE THREAD

**Issue by balk77** [robertklep/nefit-easy-http-server#15]
Hi, after upgrading to the latest versions of `nefit-easy-http-server` and `nefit-easy-core` I often get the following mesages:

`Error: MAX_RETRIES_REACHED
    at queueMessage.catch.e (/home/sander/.npm-global/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:199:51)
    at <anonymous>`

I have increased `maxRetries` to 100 but that does not help. What is the shortest interval the Bosch backend accepts when polling? By the way, it does not matter if I use `--verbose` or not, output is the same.

I have just disabled ipv6 on my Ubuntu 16.04 box. [Maybe at has to do with network issues.](https://github.com/robertklep/nefit-easy-core/issues/14) The box is wired by the way.

**Comment by robertklep** [comment]
The Bosch/Nefit servers have been going offline for quite a few times the last week or so. Next time when it happens, try and see if the iOS/Android app works. If not, it's the cloud servers that are unresponsive.

**Comment by pyrocumulus** [comment]
Same problem here. However the app wasn't working either. I powered the thermostat off and on again and restarted my docker container running nefit-easy. Afterwards it is working again. I hope this was a one time affair :)

**Comment by robertklep** [comment]
If the app doesn't work, the Nefit backend is having issues. That's been happening a lot lately :(

**Comment by pyrocumulus** [comment]
I understand. However in my situation the nefit-easy server didn't immediately resume working after I reset the thermostat. The app did however. Could nefit-easy server be lagging behind somehow? Maybe hanging in an invalid state or connection? Just out of curiosity btw.

If it happens again, I'll try the same procedure and see if the behaviour is consistent.

**Comment by robertklep** [comment]
Ah okay, yeah, the server should have resumed working. I'm still working on trying to find a fix.

**Comment by Mike-GKA** [comment]
I have the same issue "MAX_RETRIES_REACHED"
In my case this error occurred every time after getting a new IP from my internet provider.
But also occurred very seldom without that.
Stop&Restart nefit-easy works for me as a bad workaround.

**Comment by robertklep** [comment]
@Mike-GKA there's already an ongoing effort to fix this in robertklep/nefit-easy-core#14

The instructions in [this comment](https://github.com/robertklep/nefit-easy-core/issues/14#issuecomment-398140079) explain how to install a debug version of the HTTP server which may fix the problem.

**Comment by robertklep** [comment]
Hopefully fixed by `nefit-easy-http-server@5.0.1` (the latest version). Feel free to reopen this issue if the problem persists.
