### ISSUE TITLE
Password field does not support #

### ISSUE THREAD

**Issue by llagendijk** [robertklep/nefit-easy-http-server#16]
Recently I made quite a few changes to my setup including changes to my password. I used a # in it. The app on the phome supports that, but it broke the nefit-easy-http-server: It could no longer parse the json.
A minor problem once you realise what happened, but I originally suspected my nodejs setup...

**Comment by robertklep** [comment]
It's a known issue (#7).

I've already looked at it once, but couldn't find a reason why it wouldn't work: the app doesn't seem to be treating `#` characters as special. I haven't yet changed my own password to contain a `#` to debug this issue, so for now I just have to advise not to use `#` in your password ;)

**Comment by llagendijk** [comment]
no problem, I just wanted to let you know. And my current password indeed does not include a #
