### ISSUE TITLE
EADDRINUSE error

### ISSUE THREAD

**Issue by Ramnol** [robertklep/nefit-easy-http-server#18]
I'm using Domoticz on a Pi 3B. Easy-server was working but lately, after updating node-js, I get the following error:
{ Error: listen EADDRINUSE 127.0.0.1:3000
    at Server.setupListenHandle [as _listen2] (net.js:1327:14)
    at listenInCluster (net.js:1375:12)
    at doListen (net.js:1501:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 3000 }

I use node 10.4.1, npm 6.1.0, easy-server 4.0.1 and pm2 2.10.3.
I'm not really familiar with Linux.
My question: what could be wrong?
 
Many thanks for your work on this project.

Regards,
Guus.

**Comment by robertklep** [comment]
It means there's already an instance of the server running already, or you have to wait a few minutes before starting the server again.

**Comment by Jurrjuna** [comment]
Experienced the same issue (Error: listen EADDRINUSE 127.0.0.1:3000). 
Never found the cause of this issue, I solved issue by manual removing all nefit-easy-http-server and easy-server files on my Pi. 
After reinstall everything was working again.

**Comment by Ramnol** [comment]
Thanks for your replies.
Forgot that I start easy-server in rc.local at startup.
Problem solved.
