### ISSUE TITLE
SyntaxError calling http://127.0.0.1:3000/api/pressure

### ISSUE THREAD

**Issue by jaapdevries** [robertklep/nefit-easy-http-server#20]
Installed using npm command and after starting server a SyntaxError is reporterd

SyntaxError: Unexpected token c in JSON at position 0 at JSON.parse () at pending.(anonymous function).send.then.response (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-core/lib/index.js:216:30) at tryCatcher (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/util.js:16:23) at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:512:31) at Promise._settlePromise (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:569:18) at Promise._settlePromise0 (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:614:10) at Promise._settlePromises (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/promise.js:693:18) at Async._drainQueue (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:133:16) at Async._drainQueues (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:143:10) at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/bluebird/js/release/async.js:17:14) at runCallback (timers.js:696:18) at tryOnImmediate (timers.js:667:5) at processImmediate (timers.js:649:5)

**Comment by jaapdevries** [comment]
I've used an incorrect password resulting in a syntaxerror and not a error message

**Comment by robertklep** [comment]
Yeah I was going to say that it's typically due to invalid credentials :)
