### ISSUE TITLE
Set showertimer through http server

### ISSUE THREAD

**Issue by delcara** [robertklep/nefit-easy-http-server#26]
I'm using the Nefit-easy-http-server in domoticz and i'm searching for a way to set the showertimer, in the app it's possible to set this for X minutes but it resets itself after use of hot water. I asked Nefit about this and they said it was by design.

If I can set this option through the Nefit-easy-http-server then I can possibly script in dzvents that it enables again after use of hot water. 

So my question is if i can set the showertimer through the http server? I can't find anything on it in the docu.

**Comment by robertklep** [comment]
Looking at the code of the app, the relevant endpoints for the shower timer are:
* `/dhwCircuits/dhwA/extraDhw/status`: read to check the status, write (`on` or `off`) to enable/disable the timer
* `/dhwCircuits/dhwA/extraDhw/duration`: get/set the timer duration in minutes
* `/dhwCircuits/dhwA/extraDhw/supported`: read to see if your heater supports a shower timer

**Comment by delcara** [comment]
Thanks! It works. Not tested in the shower haha, but I see the changes in the Nefit App.

With below command I can switch the showertimer on: (It default to the last minutes set)
curl -XPOST http://127.0.0.1:3000/bridge/dhwCircuits/dhwA/extraDhw/status -d '{"value":"on"}' -H 'Content-Type: application/json'

And with this command I can set the duration:
curl -XPOST http://127.0.0.1:3000/bridge/dhwCircuits/dhwA/extraDhw/duration -d '{"value":8}' -H 'Content-Type: application/json'

No I can write a script that checks the status of the timer every 10 minutes, and sets it on if its off :).

**Comment by robertklep** [comment]
Thanks for testing!
