### ISSUE TITLE
Easy server blijft herstarten: missing password

### ISSUE THREAD

**Issue by michelknops** [robertklep/nefit-easy-http-server#27]
Hi,

Ik heb een "verse" easy server installatie (laatste versie pm2, npm, node.js 10) op een Raspberry PI3 met Stretch. Ik maak gebruik van PM2. Ik lees de easy server uit met Domoticz (op een andere PI).

De easy server werkt prima en ik kan alle thermostaat waardes uitlezen ook met de easy server cli etc.

Edoch echter: de easy server wordt door PM2 continu herstart omdat (blijkbaar) de server ermee stopt. De easy server error.log zegt dan ook: "missing password". Wachtwoord is echter correct aanwezig en Domoticz krijgt ook de juiste data door van Easy Server. Overige easy server logs zijn leeg (0 bytes).

Wat gaat er mis?

Michel.

**Comment by robertklep** [comment]
Het klinkt niet logisch dat het werkt én dat je "missing password" krijgt. Ik heb het vermoeden dat PM2 de server misschien meerdere keren opstart en dan ergens de juiste command line opties niet doorgeeft.

Ik heb al een tijdje niet meer met PM2 gewerkt, maar als je ergens kunt opgeven hoeveel instanties van de server opgestart moeten worden dat moet dat 1 zijn.

**Comment by michelknops** [comment]
En die klank klopte, er waren twee servers actief inderdaad. Nu krijg ik geen foutmeldingen meer.
Dank!
