### ISSUE TITLE
API request interval

### ISSUE THREAD

**Issue by justClouds** [robertklep/nefit-easy-http-server#28]
Are there any limits on the number of requests to the API (or: how is trothling at Nefit/Bosch side handled, if any)?
E.g. can I call the API /status endpoint every minute or every 5 minutes?

**Comment by robertklep** [comment]
I don't think there's any rate limiting being done, so common sense prevails. Every minute is no problem at all, every 10 seconds probably isn't either.

**Comment by justClouds** [comment]
Thanks for the quick reply!
