### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by pcdiks** [robertklep/nefit-easy-http-server#3]
I installed the software on Ubuntu 14.04 with the following command:
npm -i nefit-easy-http-server -g

The installation works well, no errors.

When I try to start the application easy-server, nothing happens.
Also trying easy-server -h does nothing.

Any ideas what could be wrong?

**Comment by robertklep** [comment]
What does `node -v` say? Installing Node.js on Ubuntu/Debian can often result in the Node executable being called `nodejs`, not `node`, which could prevent the script from starting properly.

**Comment by pcdiks** [comment]
node -v shows no output.
which node shows /usr/sbin/node and is a symlink to /usr/sbin/ax25-node

which nodejs shows /usr/bin/nodejs
/usr/bin/nodejs -v shows version v0.10.25

**Comment by robertklep** [comment]
Okay, so there's two issues here:
* Node.js is not installed as the `node` executable;
* The installed Node.js version (0.10.25) is too old, you need at least v4.0.0;

You should uninstall the `ax25-node` package (unless you're actually using it), and follow the instructions [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) to install the latest Node v4, and perhaps also (afterwards) install the `nodejs-legacy` package to install the proper symlink from `node` to `nodejs`.

**Comment by pcdiks** [comment]
Ok, that solved my problem.
Thanks
