### ISSUE TITLE
Bosch Easycontrol CT100 -> CT200 - connection error XMPP authentication failure

### ISSUE THREAD

**Issue by rskallies** [robertklep/nefit-easy-http-server#30]
I just switched the controller model from CT100 to CT200, entered the new serial, access code and my new password as before but now I get always a connection error XMPP authentication failure.

I double checked all credentials, the iOS app Bosch EasyControl works fine. Are there any recently known changes in the API / XMPP process for authentication?  

Starting the current easy-server 5.0.2 with DEBUG=* results in showing 'not-authorized' too.

**Comment by robertklep** [comment]
It looks like the CT200 uses a different authentication mechanism, someone I know that is testing the device was also getting authentication failures.

Can't really do much about it at the moment, because I don't have access to the device anymore.

**Comment by robertklep** [comment]
The only MITM "attack" I used myself was using XMPPloit to downgrade the connection to plain text by blocking `STARTTLS`, but I think more recent versions of the mobile apps don't allow that anymore :(

**Comment by cinehorse** [comment]
Gives news about CT200?

**Comment by robertklep** [comment]
@cinehorse check out [`bosch-xmpp`](https://github.com/robertklep/bosch-xmpp). I don't know it that will work with the CT200, but at least you can give it a try.

**Comment by doudz** [comment]
https://github.com/robertklep/bosch-xmpp/issues/4

**Comment by eronnes** [comment]
> I just switched the controller model from CT100 to CT200, entered the new serial, access code and my new password as before but now I get always a connection error XMPP authentication failure.
> 
> I double checked all credentials, the iOS app Bosch EasyControl works fine. Are there any recently known changes in the API / XMPP process for authentication?
> 
> Starting the current easy-server 5.0.2 with DEBUG=* results in showing 'not-authorized' too.

Did you get this working?

**Comment by rskallies** [comment]
> Am 10.03.2021 um 08:03 schrieb eronnes <notifications@github.com>:
> 
> 
> I just switched the controller model from CT100 to CT200, entered the new serial, access code and my new password as before but now I get always a connection error XMPP authentication failure.
> 
> I double checked all credentials, the iOS app Bosch EasyControl works fine. Are there any recently known changes in the API / XMPP process for authentication?
> 
> Starting the current easy-server 5.0.2 with DEBUG=* results in showing 'not-authorized' too.
> 
> Did you get this working?
> 
No I didn’t  - I had to give up on this.

**Comment by robertklep** [comment]
@eronnes @rskallies the Bosch XMPP tool has support for the CT200. It's not released to the NPM repository yet but you can install it from the [repository](https://github.com/robertklep/bosch-xmpp/). It's still work in progress.
