### ISSUE TITLE
easy-server and easy command 'hangs'

### ISSUE THREAD

**Issue by justClouds** [robertklep/nefit-easy-http-server#34]
Since a few weeks, both `easy-server -V` and `easy -V` just hangs (with or without the verbose option) and doesn't give valid output or response. Stopping/starting makes no difference, neither does reboot.

Versions:
`node -v`: v10.15.2
`npm -v`: 5.8.0
`easy-server`: 5.0.2

Where can I find a log file (nothing in daemon.log or syslog)?

**Comment by robertklep** [comment]
You mean that running `easy -V` (and _just_ that) hangs?

**Comment by justClouds** [comment]
> You mean that running `easy -V` (and _just_ that) hangs?

OK I was not very clear.

I do add the password, key and serial parameters and in the case of `easy` also the `status` command. 
I add the password, etc. because for some reason the environment variables are not picked up (message: _Error: missing password_), while `echo $NEFIT_PASSWORD` just shows the password value in the same shell session  (and the others are also defined).

For completenes: I run Debian 10. It used to work fine for months until a few weeks ago. Didn't have time to investigate/test until now.

**Comment by robertklep** [comment]
I haven't changed any code for months, so it sounds like it may have something to do with your running environment (also because it's not picking up the environment variables while they are clearly set).

Does `easy -h` work? Have you tried running in debug mode?
```
env DEBUG=* easy ...
```
(and similar for `easy-server`)

**Comment by justClouds** [comment]
With DEBUG enabled the `easy -V status` command gives:
```
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +1ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +31ms
  xmpp:connection use standard socket +2ms
  xmpp:connection setup stream +1ms
  xmpp:connection use lazy socket +1s
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +30ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="12yho9ypfg" xml:lang="en" version="1.0"> +28ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features> +24ms
```
This repeats about once every second.

**Comment by robertklep** [comment]
Sounds like a local networking issue (either something is blocking the connection to the Nefit/Bosch backend, or perhaps your Easy isn't connected to the backend for some reason).

**Comment by justClouds** [comment]
Hmm, maybe I'm blocked?
```
portqry -n wa2-mz36-qrmzh6.bosch.de -p TCP -e 80,443

Querying target system called:

 wa2-mz36-qrmzh6.bosch.de

Attempting to resolve name to IP address...

Name resolved to 139.15.227.109

querying...

TCP port 80 (http service): FILTERED

TCP port 443 (https service): FILTERED
```
And `pathping` works until somewhere in Germany where it gets timeouts (ignored ICMP, probably).
The smartphone App still works, though...

I'll keep digging into connectivity issues but I have no memory of anything firewall related that has changed lately. And this is only outbound connectivity, which is not blocked at all by my firewall (except for some specific cloud services IP's)... ;o|

**Comment by robertklep** [comment]
XMPP works on ports 5222 and 5223.

**Comment by justClouds** [comment]
Sorry about that, I wasn't thinking straight.... ;o|

**Comment by justClouds** [comment]
OK. this issue turned out to be caused by the changed default TLS version...
Changing the OpenSSL config fixed it.
