### ISSUE TITLE
node-xmpp-core error module.js:540

### ISSUE THREAD

**Issue by jbaarends** [robertklep/nefit-easy-http-server#38]
I've installed easy-server, but something keeps preventing it from running. I use a synology nas. Here are the outputs I get: 
`
root@NASDS216:/# node -v
v8.9.4
root@NASDS216:/# npm -v
5.6.0
root@NASDS216:/# easy-server
module.js:540
    throw err;
    ^

Error: Cannot find module 'node-xmpp-core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/lib/scram-auth-mechanism.js:4:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/lib/index.js:10:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
`
Consequently, Domoticz keeps reporting it cannot get any data. Well, that's unfortunate, but first I need to get easy-server running. Any ideas? I'm a huge noob, so if you can provide me with the specific codes I need to insert into putty, than that would be super helpfull.

**Comment by robertklep** [comment]
How did you install the server to begin with?

**Comment by jbaarends** [comment]
I like to think so (see code below). But, I'm a huge noob and still learning basics, so it could be that I'm mistaken...

`
root@NASDS216:~# sudo npm i nefit-easy-http-server -g
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
/volume2/@appstore/Node.js_v8/usr/local/bin/easy-server -> /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
+ nefit-easy-http-server@5.0.2
updated 1 package in 16.17s
root@NASDS216:~# easy-server -v
module.js:540
    throw err;
    ^

Error: Cannot find module 'node-xmpp-core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/lib/scram-auth-mechanism.js:4:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/lib/index.js:10:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
`

**Comment by robertklep** [comment]
It works for me on my Synology, so it's not specifically related to that.

I've had issues like this before (in a completely different environment) caused by a file called `package-lock.json` being present in the directory from which you start `npm`. Try and see if this works:
```
cd ~
rm package-lock.json
npm i nefit-easy-http-server -g
```

**Comment by jbaarends** [comment]
No luck :-( Could it have something to do with my appstore being located on volume 2 (in most tutorials I see them located on volume1)?

`root@NASDS216:~# cd ~
root@NASDS216:~# rm package-lock.json
root@NASDS216:~# npm i nefit-easy-http-server -g
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
/volume2/@appstore/Node.js_v8/usr/local/bin/easy-server -> /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
+ nefit-easy-http-server@5.0.2
updated 1 package in 11.255s
root@NASDS216:~# easy-server -v
module.js:540
    throw err;
    ^

Error: Cannot find module 'node-xmpp-core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/lib/scram-auth-mechanism.js:4:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/nefit-easy-http-server/node_modules/nefit-easy-commands/node_modules/nefit-easy-core/lib/index.js:10:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
`

**Comment by robertklep** [comment]
The volume shouldn't be a problem.

Try doing a local install to see if that will work:
```
cd /tmp
npm i nefit-easy-http-server
./node_modules/.bin/easy-server -h
```

If that works, it's something related to the global package directory. If you don't have any other Node.js modules/projects installed, perhaps you could try uninstalling the Node.js package, removing `/volume2/@appstore/Node.js_v8/usr/local/lib/node_modules`, and re-installing the package again.

**Comment by jbaarends** [comment]
I've removed the node.jsV8 package via Package Center, and checked whether there was anything left in the /volume2/@appstore/. There wasn't. So that's good. Now, I reinstalled Node.jsV8 via package center. Then `I ran sudo npm i nefit-easy-http-server -g`. That went oke. Then I tried `easy-server -v`, and it says: 'No such file or directory'. I look into the folder /usr/local/bin and there I see easy-server. However, when I try to start it, it says  it doesn't exist. Any ideas?

`root@NASDS216:~# node -v
-ash: /usr/local/bin/node: No such file or directory
root@NASDS216:~# npm -v
-ash: /usr/local/bin/npm: No such file or directory
root@NASDS216:~# cd /volume2/@appstore/
root@NASDS216:/volume2/@appstore# dir
total 48
drwxr-xr-x  11 root         root         4096 Aug  6 10:53 .
drwxr-xr-x  16 root         root         4096 Aug  5 22:35 ..
drwxr-xr-x  15 AudioStation AudioStation 4096 May 23 19:48 AudioStation
drwxr-xr-x+ 12          100 root         4096 Aug  4 22:51 domoticz
drwxr-xr-x   5 root         root         4096 Jul 26 09:47 Java8
drwxr-xr-x   4 root         root         4096 Aug  6 10:53 Node.js_v8
drwxr-xr-x   7 root         root         4096 Jun  4 05:09 PHP5.6
drwxr-xr-x   7 root         root         4096 Jan 15  2019 PHP7.0
drwxr-xr-x   5 root         root         4096 Jul 30 23:22 PHP7.2
drwxr-xr-x  16 VideoStation VideoStation 4096 Jun 22 08:01 VideoStation
drwxr-xr-x  14 root         root         4096 Jul 30 15:11 WebStation
root@NASDS216:/volume2/@appstore# cd
root@NASDS216:~# sudo npm i nefit-easy-http-server -g
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
/volume2/@appstore/Node.js_v8/usr/local/bin/easy-server -> /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
+ nefit-easy-http-server@5.0.2
added 135 packages in 21.744s
root@NASDS216:~# easy-server -h
-ash: /usr/local/bin/easy-server: No such file or directory
root@NASDS216:~# cd /usr/local/bin/easy-server
-ash: cd: /usr/local/bin/easy-server: No such file or directory
root@NASDS216:~# cd /usr/local/bin/
root@NASDS216:/usr/local/bin# dir
total 20
drwxr-xr-x 3 root root 4096 Aug  6 10:53 .
drwxr-xr-x 9 root root 4096 Aug  6 10:53 ..
lrwxrwxrwx 1 root root   58 Aug  4 15:00 easy-server -> ../lib/node_modules/nefit-easy-http-server/bin/easy-server
drwxr-xr-x 5 root root 4096 Mar 27  2017 feasibilitycheck
lrwxrwxrwx 1 root root   48 Aug  6 10:53 node -> /volume2/@appstore/Node.js_v8/usr/local/bin/node
lrwxrwxrwx 1 root root   46 Aug  6 10:53 npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
-rwxr-xr-x 1 root root 7968 Aug  6 10:53 nvm
lrwxrwxrwx 1 root root   47 Aug  5 19:38 php56 -> /var/packages/PHP5.6/target/usr/local/bin/php56
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php56-cgi -> /var/packages/PHP5.6/target/usr/local/bin/php56-cgi
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php56-fpm -> /var/packages/PHP5.6/target/usr/local/bin/php56-fpm
lrwxrwxrwx 1 root root   47 Aug  5 19:38 php70 -> /var/packages/PHP7.0/target/usr/local/bin/php70
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php70-cgi -> /var/packages/PHP7.0/target/usr/local/bin/php70-cgi
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php70-fpm -> /var/packages/PHP7.0/target/usr/local/bin/php70-fpm
lrwxrwxrwx 1 root root   47 Aug  5 19:38 php72 -> /var/packages/PHP7.2/target/usr/local/bin/php72
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php72-cgi -> /var/packages/PHP7.2/target/usr/local/bin/php72-cgi
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php72-fpm -> /var/packages/PHP7.2/target/usr/local/bin/php72-fpm
lrwxrwxrwx 1 root root   50 Aug  5 19:38 phpdbg56 -> /var/packages/PHP5.6/target/usr/local/bin/phpdbg56
lrwxrwxrwx 1 root root   50 Aug  5 19:38 phpdbg70 -> /var/packages/PHP7.0/target/usr/local/bin/phpdbg70
lrwxrwxrwx 1 root root   50 Aug  5 19:38 phpdbg72 -> /var/packages/PHP7.2/target/usr/local/bin/phpdbg72
root@NASDS216:/usr/local/bin#
`

By the way: huge thanks for taking the time looking into this. Really appreciated! :-)

**Comment by robertklep** [comment]
Try this:
```
/usr/local/bin/easy-server
```
(without the `cd`, which means "change directory")

Perhaps you need to re-start your login session (I assume through SSH) for it to be picked up.

**Comment by jbaarends** [comment]
Started a new session: 

root@NASDS216:~# /usr/local/bin/easy-server
-ash: /usr/local/bin/easy-server: No such file or directory
root@NASDS216:~# easy-server
-ash: easy-server: command not found
root@NASDS216:~# ^C
root@NASDS216:~# cd /usr/local/bin
root@NASDS216:/usr/local/bin# dir
total 20
drwxr-xr-x 3 root root 4096 Aug  6 10:53 .
drwxr-xr-x 9 root root 4096 Aug  6 10:53 ..
lrwxrwxrwx 1 root root   58 Aug  4 15:00 easy-server -> ../lib/node_modules/nefit-easy-http-server/bin/easy-server
drwxr-xr-x 5 root root 4096 Mar 27  2017 feasibilitycheck
lrwxrwxrwx 1 root root   48 Aug  6 10:53 node -> /volume2/@appstore/Node.js_v8/usr/local/bin/node
lrwxrwxrwx 1 root root   46 Aug  6 10:53 npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
-rwxr-xr-x 1 root root 7968 Aug  6 10:53 nvm
lrwxrwxrwx 1 root root   47 Aug  5 19:38 php56 -> /var/packages/PHP5.6/target/usr/local/bin/php56
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php56-cgi -> /var/packages/PHP5.6/target/usr/local/bin/php56-cgi
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php56-fpm -> /var/packages/PHP5.6/target/usr/local/bin/php56-fpm
lrwxrwxrwx 1 root root   47 Aug  5 19:38 php70 -> /var/packages/PHP7.0/target/usr/local/bin/php70
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php70-cgi -> /var/packages/PHP7.0/target/usr/local/bin/php70-cgi
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php70-fpm -> /var/packages/PHP7.0/target/usr/local/bin/php70-fpm
lrwxrwxrwx 1 root root   47 Aug  5 19:38 php72 -> /var/packages/PHP7.2/target/usr/local/bin/php72
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php72-cgi -> /var/packages/PHP7.2/target/usr/local/bin/php72-cgi
lrwxrwxrwx 1 root root   51 Aug  5 19:38 php72-fpm -> /var/packages/PHP7.2/target/usr/local/bin/php72-fpm
lrwxrwxrwx 1 root root   50 Aug  5 19:38 phpdbg56 -> /var/packages/PHP5.6/target/usr/local/bin/phpdbg56
lrwxrwxrwx 1 root root   50 Aug  5 19:38 phpdbg70 -> /var/packages/PHP7.0/target/usr/local/bin/phpdbg70
lrwxrwxrwx 1 root root   50 Aug  5 19:38 phpdbg72 -> /var/packages/PHP7.2/target/usr/local/bin/phpdbg72
root@NASDS216:/usr/local/bin#

This means that easy-server is in the right place right? However it won't start for some reason?

**Comment by robertklep** [comment]
What does this output?
```
env node -h
```

**Comment by jbaarends** [comment]
root@NASDS216:~# env node -h
Usage: node [options] [ -e script | script.js | - ] [arguments]
       node inspect script.js [arguments]

Options:
  -v, --version              print Node.js version
  -e, --eval script          evaluate script
  -p, --print                evaluate script and print result
  -c, --check                syntax check script without executing
  -i, --interactive          always enter the REPL even if stdin
                             does not appear to be a terminal
  -r, --require              module to preload (option can be repeated)
  -                          script read from stdin (default; interactive mode if a tty)
  --inspect[=[host:]port]    activate inspector on host:port
                             (default: 127.0.0.1:9229)
  --inspect-brk[=[host:]port]
                             activate inspector on host:port
                             and break at start of user script
  --inspect-port=[host:]port
                             set host:port for inspector
  --no-deprecation           silence deprecation warnings
  --trace-deprecation        show stack traces on deprecations
  --throw-deprecation        throw an exception on deprecations
  --pending-deprecation      emit pending deprecation warnings
  --no-warnings              silence all process warnings
  --napi-modules             load N-API modules (no-op - option
                             kept for compatibility)
  --abort-on-uncaught-exception
                             aborting instead of exiting causes a
                             core file to be generated for analysis
  --trace-warnings           show stack traces on process warnings
  --redirect-warnings=file
                             write warnings to file instead of
                             stderr
  --trace-sync-io            show stack trace when use of sync IO
                             is detected after the first tick
  --force-async-hooks-checks
                             enables checks for async_hooks
  --trace-events-enabled     track trace events
  --trace-event-categories   comma separated list of trace event
                             categories to record
  --track-heap-objects       track heap object allocations for heap snapshots
  --prof-process             process v8 profiler output generated
                             using --prof
  --zero-fill-buffers        automatically zero-fill all newly allocated
                             Buffer and SlowBuffer instances
  --v8-options               print v8 command line options
  --v8-pool-size=num         set v8's thread pool size
  --tls-cipher-list=val      use an alternative default TLS cipher list
  --use-bundled-ca           use bundled CA store (default)
  --use-openssl-ca           use OpenSSL's default CA store
  --openssl-config=file      load OpenSSL configuration from the
                             specified file (overrides
                             OPENSSL_CONF)
  --icu-data-dir=dir         set ICU data load path to dir
                             (overrides NODE_ICU_DATA)
  --preserve-symlinks        preserve symbolic links when resolving
  --experimental-modules     experimental ES Module support
                             and caching modules

Environment variables:
NODE_DEBUG                   ','-separated list of core modules
                             that should print debug information
NODE_DISABLE_COLORS          set to 1 to disable colors in the REPL
NODE_EXTRA_CA_CERTS          path to additional CA certificates
                             file
NODE_ICU_DATA                data path for ICU (Intl object) data
NODE_NO_WARNINGS             set to 1 to silence process warnings
NODE_NO_HTTP2                set to 1 to suppress the http2 module
NODE_OPTIONS                 set CLI options in the environment
                             via a space-separated list
NODE_PATH                    ':'-separated list of directories
                             prefixed to the module search path
NODE_PENDING_DEPRECATION     set to 1 to emit pending deprecation
                             warnings
NODE_REPL_HISTORY            path to the persistent REPL history
                             file
NODE_REDIRECT_WARNINGS       write warnings to path instead of
                             stderr
OPENSSL_CONF                 load OpenSSL configuration from file

Documentation can be found at https://nodejs.org/
root@NASDS216:~#

**Comment by robertklep** [comment]
Okay, so that works. Next to try:
```
env node /usr/local/bin/easy-server -h
```

**Comment by jbaarends** [comment]
That gives: 

root@NASDS216:~# env node /usr/local/bin/easy-server -h
module.js:540
    throw err;
    ^

Error: Cannot find module '/usr/local/bin/easy-server'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
root@NASDS216:~#

**Comment by robertklep** [comment]
Hmm, that would mean that the symlink in `/usr/local/bin` is broken. What does this return:
```
ls -al /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
```

**Comment by jbaarends** [comment]
root@NASDS216:~# ls -al /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
-rwxr-xr-x 1 root root 46 Aug  6 10:54 /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
root@NASDS216:~#

**Comment by robertklep** [comment]
Next try:
```
env node /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server -h
```

**Comment by jbaarends** [comment]
We are getting somewhere! This gives: 

`root@NASDS216:~# env node /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server -h
easy-server – Nefit Easy™ HTTP-server

Usage:
  easy-server [options]

Options:
  -h --help                Show this screen
  -v --version             Show version
  -V --verbose             Be more verbose
  --serial=SERIAL          Nefit Easy™ serial number
  --access-key=ACCESS_KEY  Nefit Easy™ access key
  --password=PASSWORD      Nefit Easy™ password
  --port=PORT              Port to listen on [default: 3000]
  --host=HOST              Host to bind to [default: 127.0.0.1]
  --timeout=TIMEOUT        Request timeout in seconds [default: 30]

Instead of specifying serial number, access key or password through
options, you can also define them through environment variables:

  NEFIT_SERIAL_NUMBER
  NEFIT_ACCESS_KEY
  NEFIT_PASSWORD

root@NASDS216:~#`

**Comment by robertklep** [comment]
Okay, we're close! I still don't understand why the version installed in `/usr/local/bin` doesn't work, but perhaps it's a dangling symlink so we can try to fix it:
```
cd /usr/local/bin
rm easy-server
ln -s /volume2/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server easy-server
```

**Comment by jbaarends** [comment]
YES!! Thank you so much! It works, immediately in Domoticz as well. You are the best! Thank you for your generosity in putting the time and effort in my setup!

**Comment by robertklep** [comment]
Good to hear you got it working! Have fun using it :D

**Comment by smausje** [comment]
i try to run nefit easy on my synology but ik wont work, get this message

root@NAS_play:~# npm i nefit-easy-http-server -g
npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
/volume1/@appstore/Node.js_v8/usr/local/bin/easy-server -> /volume1/@appstore/Node.js_v8/usr/local/lib/node_modules/nefit-easy-http-server/bin/easy-server
+ nefit-easy-http-server@5.0.2
added 136 packages from 124 contributors in 19.073s
root@NAS_play:~# easy-server --serial=********* --access-key=******** --password=*****
-ash: easy-server: command not found

can you help me?

**Comment by robertklep** [comment]
You need to add `/volume1/@appstore/Node.js_v8/usr/local/bin/` to your `$PATH`, or otherwise start the server using it's full path:
```
/volume1/@appstore/Node.js_v8/usr/local/bin/easy-server --serial=********* --access-key=******** --password=*****
```

**Comment by smausje** [comment]
it works thanks, now i wil look for a autostart for the server.

**Comment by Frenkie64** [comment]
Hi Robert,
I have a small similar issue. I can't get the Nefit-Easy-HTTP-server to install in the correct folder on my Synology. In my case it is added to 
/volume1/@appstore/Node.js_v6/usr/local/lib/node_modules/nefit-easy-http-server/bin
I can get it to start from there, but I'm not really sure how to add it to the $PATH variable (I'm more of a Windows guy) or how to get it working from this script:
https://www.domoticz.com/forum/viewtopic.php?f=56&t=9653&start=680#p197643

Can you assist me with this one?
