### ISSUE TITLE
New NAS DS220Plus : XMPP authentication failure

### ISSUE THREAD

**Issue by Gericom-nw** [robertklep/nefit-easy-http-server#46]
Hi, i installed Easy-server on a new nas DS220Plus (before it was working on a DS216J), but now i got XMPP authentication failure when starting the easy-server. what am I doing wrong?

xx@DS220Plus:/usr/local/bin$

npm -v
5.6.0
node -v
8.9.4
easy-server -v
5.0.3

sudo easy-server --serial=xx --access-key=xx --password=xx
Password: XX
XMPP authentication failure

**Comment by robertklep** [comment]
XMPP authentication uses the serial number and the access key (not the password), so make sure those are correct. If any of those values contains hyphens (`-`), remove them.

**Comment by Gericom-nw** [comment]
As it turns out there was one character missing from the access key. Probably made a mistake when noting it down somewhere.
It is working again now. Thanks for the response, regardless.
