### ISSUE TITLE
No acces :3000

### ISSUE THREAD

**Issue by TGMivo** [robertklep/nefit-easy-http-server#48]
Whenn i start the Cli it works (short time)
 easy-server --serial=(Serial) --access-key=(Key)--password=(Pass)

pi@raspberrypi:~ $ sudo curl http://127.0.0.1:3000/bridge/ecus/rrc/uiStatus
curl: (7) Failed to connect to 127.0.0.1 port 3000: Verbinding is geweigerd

What can i do?

**Comment by robertklep** [comment]
Are you running `easy-server` and `curl` on the same machine?

If so, you can run the server in debug mode so it should log more information on what's going on:
```
env DEBUG=* easy-server --serial=(Serial) --access-key=(Key)--password=(Pass)
```

If not, then instead of `127.0.0.1` you need to use the IP-address of the machine the server is running on.

**Comment by TGMivo** [comment]
xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +5ms
  xmpp:connection use lazy socket +3ms
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +77ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="5wc3631z3j" xml:lang="en" version="1.0"> +33ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features> +33ms
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +2ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +32ms
  xmpp:connection use standard socket +29ms
  xmpp:connection setup stream +0ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +147ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="5wc3631z3j" xml:lang="en" version="1.0"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features> +27ms
  xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">biwsbj1ycmNjb250YWN0XzcyMDkyNDgxMCxyPTI3MThmNDdlZGMxODc4OWU5MDdiZWNjZDYzMTliYWMz</auth> +9ms
  xmpp:connection receive: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj0yNzE4ZjQ3ZWRjMTg3ODllOTA3YmVjY2Q2MzE5YmFjM2Q4NGM0ZGUyLWZlNzQtNDAyMi1iODY2LWRlN2JjOWFlMjQyOSxzPW5hQS8zd25ETGhqcDF1NmlTbExFMXpNQzRsazNWeDhHLGk9NDA5Ng==</challenge> +40ms
  xmpp:connection send: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1iaXdzLHI9MjcxOGY0N2VkYzE4Nzg5ZTkwN2JlY2NkNjMxOWJhYzNkODRjNGRlMi1mZTc0LTQwMjItYjg2Ni1kZTdiYzlhZTI0MjkscD1RYVpua0dEMDhyK215T1NsbHVoNE5LMCtrRzA9</response> +600ms
  xmpp:connection receive: <success xmlns="urn:ietf:params:xml:ns:xmpp-sasl">dj1zc0dXWEFXRWd4bVkrYmpOaGRUc2wrMlYvMUE9</success> +36ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +1ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="5wc3631z3j" xml:lang="en" version="1.0"><stream:features><ver xmlns="urn:xmpp:features:rosterver"/><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/><session xmlns="urn:ietf:params:xml:ns:xmpp-session"><optional/></session></stream:features> +31ms
  xmpp:connection send: <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"/> +2ms
  xmpp:connection receive: <iq type="result" id="bind" to="wa2-mz36-qrmzh6.bosch.de/5wc3631z3j"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>rrccontact_720924810@wa2-mz36-qrmzh6.bosch.de/5wc3631z3j</jid></bind></iq> +33ms
  xmpp:connection send: <session xmlns="urn:ietf:params:xml:ns:xmpp-session"/> +1ms
  xmpp:connection receive: <iq type="result" id="sess" from="wa2-mz36-qrmzh6.bosch.de" to="rrccontact_720924810@wa2-mz36-qrmzh6.bosch.de/5wc3631z3j"/> +33ms
  nefit-easy-core online, jid = rrccontact_720924810@wa2-mz36-qrmzh6.bosch.de/5wc3631z3j +0ms
  xmpp:connection send: <presence/> +3ms
  express:application set "x-powered-by" to true +129ms
  express:application set "etag" to 'weak' +2ms
  express:application set "etag fn" to [Function: generateETag] +1ms
  express:application set "env" to 'development' +3ms
  express:application set "query parser" to 'extended' +0ms
  express:application set "query parser fn" to [Function: parseExtendedQueryString] +1ms
  express:application set "subdomain offset" to 2 +0ms
  express:application set "trust proxy" to false +0ms
  express:application set "trust proxy fn" to [Function: trustNone] +1ms
  express:application booting in development mode +1ms
  express:application set "view" to [Function: View] +0ms
  express:application set "views" to '/home/pi/views' +1ms
  express:application set "jsonp callback name" to 'callback' +0ms
  express:router use '/' query +7ms
  express:router:layer new '/' +1ms
  express:router use '/' expressInit +1ms
  express:router:layer new '/' +1ms
  express:router use '/' corsMiddleware +0ms
  express:router:layer new '/' +0ms
  express:router use '/' logger +11ms
  express:router:layer new '/' +0ms
  express:router use '/' jsonParser +2ms
  express:router:layer new '/' +0ms
  express:router:route new '*' +1ms
  express:router:layer new '*' +0ms
  express:router:route get '*' +1ms
  express:router:layer new '/' +0ms
  express:router:route post '*' +1ms
  express:router:layer new '/' +0ms
  express:router use '/bridge' router +0ms
  express:router:layer new '/bridge' +1ms
  express:router:route new '/:command' +0ms
  express:router:layer new '/:command' +1ms
  express:router:route get '/:command' +0ms
  express:router:layer new '/' +1ms
  express:router use '/api' router +0ms
  express:router:layer new '/api' +0ms
  express:router use '/' <anonymous> +1ms
  express:router:layer new '/' +0ms
HTTP server listening on http://127.0.0.1:3000

**Comment by robertklep** [comment]
I don't see any issues there, the server is starting up just fine.

As I previously asked: are you running easy-server and curl on the same machine?

**Comment by TGMivo** [comment]
Hmm yes, that was no problem before. I removed curl now

**Comment by robertklep** [comment]
It doesn't really make sense that you get the error "Failed to connect to 127.0.0.1 port 3000: Verbinding is geweigerd" while the server is still running and curl is executed on the same RPi.

**Comment by TheFons-01** [comment]
Well... I have the same issue, 
`pi@homefons:~ $ curl http://127.0.0.1:3000/api/status
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused`

and my pm2 logs gives :
`0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:56 GMT xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:56 GMT xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:56 GMT xmpp:connection use standard socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:56 GMT xmpp:connection setup stream
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection use lazy socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection setup stream
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="8wefool9d9" xml:lang="en" version="1.0">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection use standard socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:57 GMT xmpp:connection setup stream
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection use lazy socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection setup stream
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="2b2fi6fy32" xml:lang="en" version="1.0">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection use standard socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 00:37:58 GMT xmpp:connection setup stream
`
looks like a connection being set up but not consumed ??
same strings keep repeating

**Comment by TheFons-01** [comment]
and yes, its on the same machine so 127.0.0.1 should work,

**Comment by robertklep** [comment]
@TheFons-01 have you read this? https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions

**Comment by TheFons-01** [comment]
Yes I have read this, I have changed it several times back and forth. WITH the advised ssl changes I get the following logs, and still have no connection to the Bosch server AND have the connection refused in the port 3000 on the localhost (127.0.0.1):
I have put the Serial, the access-key and the password in the env. variables to shorten typing, I echo-ed these to verify their contents, all to no avail. I used the several websites with the install scripts for the Nefit-easy, all have the same steps, I have reinstalled the Pi4 several times from scratch.  

`PM2                    | App [nefiteasyhttpserver:0] starting in -fork mode-
PM2                    | App [nefiteasyhttpserver:0] online
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:client:session start socket connection
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection setup socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection use lazy socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection setup stream
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="3xvdap7x4k" xml:lang="en" version="1.0">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection use standard socket
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:18 GMT xmpp:connection setup stream
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:21 GMT xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de">
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:21 GMT xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="3xvdap7x4k" xml:lang="en" version="1.0"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:21 GMT xmpp:connection send: <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="SCRAM-SHA-1">biwsbj1ycmNjb250YWN0XzYyMFwyMDk1MlwyMDM3OSxyPWMyZDQ1NGIzMDUxYTYyODY1OTkwOTRlMzcwOTdiODA3</auth>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:21 GMT xmpp:connection receive: <challenge xmlns="urn:ietf:params:xml:ns:xmpp-sasl">cj1jMmQ0NTRiMzA1MWE2Mjg2NTk5MDk0ZTM3MDk3YjgwN2ZkM2QxYzA2LTY2OTMtNDVlNS05NWMzLTVmODJjYTBlN2QyZCxzPTRSd2RVam1WR29YSDZxL2pFZ1lvQWFWOUo0QzRIQldjLGk9NDA5Ng==</challenge>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:22 GMT xmpp:connection send: <response xmlns="urn:ietf:params:xml:ns:xmpp-sasl">Yz1iaXdzLHI9YzJkNDU0YjMwNTFhNjI4NjU5OTA5NGUzNzA5N2I4MDdmZDNkMWMwNi02NjkzLTQ1ZTUtOTVjMy01ZjgyY2EwZTdkMmQscD0rcVBJaGNiTlR5OG42cjRPNEpueWM4NUpZOUU9</response>
0|nefiteasyhttpserver  | Tue, 12 Jan 2021 20:15:22 GMT xmpp:connection receive: <failure xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><not-authorized/></failure>
0|nefiteasyhttpserver  | 2021-01-12T20:15:22.498Z nefit-easy-core connection error XMPP authentication failure
0|nefiteasyhttpserver  | XMPP authentication failure
PM2                    | App [nefiteasyhttpserver:0] exited with code [1] via signal [SIGINT]
PM2                    | App [nefiteasyhttpserver:0] starting in -fork mode-
PM2                    | App [nefiteasyhttpserver:0] online
^C
pi@homefons:~ $ ^C
pi@homefons:~ $ pm2 list
┌─────┬────────────────────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name                   │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼────────────────────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ nefiteasyhttpserver    │ default     │ N/A     │ fork    │ 23498    │ 1s     │ 397  │ online    │ 0%       │ 2.5mb    │ pi       │ disabled │
└─────┴────────────────────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘
pi@homefons:~ $ curl http://127.0.0.1:3000/api/status
curl: (7) Failed to connect to 127.0.0.1 port 3000: Connection refused
`

**Comment by TheFons-01** [comment]
SOLVED
Ok, Very interesting: 
The Access-key AND the Serial-number have to be entered WITHOUT Spaces, so my serial number is something like "620 XXX xxx" you have to enter it like "620XXXxxx" !!
The same with the access-key, it has a 4-four letternumber sequences... but the program needs 16 letters/nums tied together, no spaces!!
In the NEFIT App and on the backside of the thermostate these are all WITH the spaces. So I used those sequences: resulting in no authentication, AND resulting in not starting the HTTP server on port 3000. so there is your "connection refused"
I hope this can be added on the several setup guides
Thing is now working in Domoticz also

**Comment by robertklep** [comment]
@TheFons-01 sorry for the confusion :( I updated the README to reflect that the access key and serial number should be passed without whitespace.
