### ISSUE TITLE
spikes in values gas usage

### ISSUE THREAD

**Issue by nelizzzz** [robertklep/nefit-easy-http-server#6]
See https://www.domoticz.com/forum/viewtopic.php?f=6&t=17052. Not sure if it's a bug in Domoticz or in the http-server.

**Comment by robertklep** [comment]
I found [this post](https://www.domoticz.com/forum/viewtopic.php?t=14200) which mentions the exact same value, and it doesn't mention Nefit so I'm inclined to think it's a Domoticz issue (perhaps a negative value being stored in an unsigned variable).

**Comment by nelizzzz** [comment]
Ok thanks!
